# Pokélecture — single static binary + content, ~30 MB image.
#
# One thing to know about the voice: the .m4a track is generated by macOS `say`,
# which does not exist on Linux. So the build COPIES web/audio from the build
# context rather than generating it — and because the deployed host builds from a
# clone of the repo, that directory is committed. Build a context without it and
# the game falls back to the browser's own French voice, which on an Android
# tablet means silence: no fr voice is guaranteed to be installed.
#
# Sprites are different — they are plain HTTP downloads, so the build fetches
# them itself and they never need to be committed.

# ---------------------------------------------------------------- build ------
FROM golang:1.26-alpine AS build

WORKDIR /src
COPY go.mod ./
RUN go mod download

COPY cmd/ ./cmd/
COPY internal/ ./internal/
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /out/pokelecture ./cmd/pokelecture \
 && CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /out/pokecontent ./cmd/pokecontent

# --------------------------------------------------------------- assets ------
FROM build AS assets

RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY data/ ./data/
COPY web/ ./web/

# Fail the build on undecodable content rather than shipping it to a five-year-old.
RUN /out/pokecontent check -root /app

# Pokémon artwork, straight from PokeAPI.
RUN /out/pokecontent sprites -root /app

# -------------------------------------------------------------- runtime ------
FROM alpine:3.20

RUN apk add --no-cache ca-certificates tzdata wget \
 && adduser -D -u 10001 poke

WORKDIR /app
COPY --from=build  /out/pokelecture  /usr/local/bin/pokelecture
COPY --from=build  /out/pokecontent  /usr/local/bin/pokecontent
COPY --from=assets /app/data/        ./data/
COPY --from=assets /app/web/         ./web/

# var/ holds the savegame, web/audio/recorded/ the parent's own recordings.
# Both are mounted as volumes in compose; created here so a bare `docker run` works.
RUN mkdir -p var web/audio/recorded && chown -R poke:poke /app

USER poke

# POKELECTURE_NAME is deliberately left unset: set it and it overrides the name
# in the savegame at every start, leave it and the savegame keeps the name it
# already has (falling back to "Dresseur" on a fresh one). Baking a default in
# here would silently rename the child back on any start that forgot the var.
ENV POKELECTURE_ADDR=:8080 \
    POKELECTURE_ROOT=/app \
    POKELECTURE_BASE=/

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=4s --start-period=5s --retries=3 \
  CMD wget -qO- "http://127.0.0.1:8080${POKELECTURE_BASE}api/state" >/dev/null || exit 1

CMD ["pokelecture"]
